spring.application.name=eduManager
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/eduManager
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Springdoc / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

openai.api.key=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
openai.model=gpt-4o
